// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnqcmkatgrbrqiurjaas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InducWNta2F0Z3JicnFpdXJqYWFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNjU0NDUsImV4cCI6MjA2NDY0MTQ0NX0.NDrhqeS9C8SYGVw28w-yEmcNuL5gf5La3IUp2lMkQHM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);